Added line to actually create influx ddtabase.

diff --git a/files/user-data b/files/user-data
--- a/files/user-data
+++ b/files/user-data
@@ -1,14 +1,16 @@
 #!/bin/bash
 
-sudo apt-get install -y apt-transport-https
-sudo apt-get install -y software-properties-common wget
+exec 1>>install.log
 
-wget -qO- https://repos.influxdata.com/influxdb.key | sudo apt-key add -
+apt-get install -y apt-transport-https
+apt-get install -y software-properties-common wget
+
+wget -qO- https://repos.influxdata.com/influxdb.key | apt-key add -
 source /etc/lsb-release
-echo "deb https://repos.influxdata.com/${DISTRIB_ID,,} ${DISTRIB_CODENAME} stable" | sudo tee /etc/apt/sources.list.d/influxdb.list
+echo "deb https://repos.influxdata.com/${DISTRIB_ID,,} ${DISTRIB_CODENAME} stable" | tee /etc/apt/sources.list.d/influxdb.list
 
-wget -q -O - https://packages.grafana.com/gpg.key | sudo apt-key add -
-echo "deb https://packages.grafana.com/enterprise/deb stable main" | sudo tee -a /etc/apt/sources.list.d/grafana.list 
+wget -q -O - https://packages.grafana.com/gpg.key | apt-key add -
+echo "deb https://packages.grafana.com/enterprise/deb stable main" | tee -a /etc/apt/sources.list.d/grafana.list 
 
 apt -y update
 apt -y install grafana-enterprise
@@ -27,3 +29,5 @@ systemctl daemon-reload
 systemctl restart influxdb
 systemctl restart grafana-server
 systemctl restart nginx
+
+echo "CREATE DATABASE perf" | influx || die "Error creating influx database."
